version: "3"
services:
  frontend:
    build: ./shopping-cart-frontend
    ports:
    - "4200:4200"
    volumes:
    - ./shopping-cart-frontend/src:/app/src
  postgres:
    build: ./shopping-cart-backend/postgres-docker
    restart: always
    environment:
      - POSTGRES_USER=semantive
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=semantive
  backend:
    build: ./shopping-cart-backend
    ports:
    - "8080:8080"
    volumes:
      - ./shopping-cart-backend/src/:/app/src/