version: "3"
services:
  frontend:
    build: ./shopping-cart-frontend
    ports:
    - "4200:4200"
    volumes:
    - ./shopping-cart-frontend/src:/app/src
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=semantive
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=semantive